#!/bin/bash
######################################################################
# Wrapper script to activate a python3 virtual environemnt project   #
# using the "python3 venv utility.                                   #
######################################################################

usage() {
  echo "Usage:  source workon projectName"
}

if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
  # echo "script ${BASH_SOURCE[0]} is being sourced ..."
  
  if [ -z "$VENV_PROJECTS" ]; then
    export VENV_PROJECTS=$HOME/venv_projects
  fi

  if [ -z "$1" ]; then
    echo "Existing projects are..."
    ls -w 1 $VENV_PROJECTS
    
  else
    cd $VENV_PROJECTS/$1
    source .venv/bin/activate
  fi
  
else
  echo "script NOT being sourced ..."
  usage
fi
